name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  # Change

  ## Closed Issues 🎉

  CLOSED_ISSUES

  ## PRs 🚀

  $CHANGES

  ## Thanks Contributors 👏

  $CONTRIBUTORS

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
categories:
  - title: 'Breaking'
    label: 'type: breaking'
  - title: 'New'
    label: 'type: feature'
  - title: 'Bug Fixes'
    label: 'type: bug'
  - title: 'Maintenance'
    label: 'type: maintenance'
  - title: 'Documentation'
    label: 'type: docs'
  - title: 'Other changes'
  - title: 'Dependency Updates'
    label: 'type: dependencies'
    collapse-after: 5

change-template: '- $TITLE (#$NUMBER)'

version-resolver:
  major:
    labels:
      - 'type: breaking'
  minor:
    labels:
      - 'type: feature'
  patch:
    labels:
      - 'type: bug'
      - 'type: maintenance'
      - 'type: docs'
      - 'type: dependencies'
      - 'type: security'

exclude-labels:
  - 'skip-changelog'
