name: Confirm release

on:
  push:
    branches:
      - main

jobs:
  confirm_release:
    runs-on: ubuntu-latest
    steps:
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v2
      - name: Extract release ID
        uses: actions/github-script@v6
        with:
          script: |
            const body = '${{ github.event.body }}'
            const match = body.match(/<!-- draft_release_id=(?<releaseId>.+) -->/);
            const releaseId = match.groups?.releaseId;
            if (!releaseId) {
                core.setFailed(`リリースIDを取得できませんでした`);
            }

            core.debug(`releaseId: ${releaseId}`);
            
            octokit.rest.repos.updateRelease({
              owner: "${{ github.repository_owner	 }}",
              repo: "${{ github.repository }}".split('/')[1],
              release_id: Number(releaseId),
              make_latest: 'true'
            });


