name: Confirm release

on:
  push:
    branches:
      - main

jobs:
  confirm_release:
    runs-on: ubuntu-latest
    steps:
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v2
      - name: Extract release ID
        uses: actions/github-script@v6
        with:
          script: |
            const owner = "${{ github.repository_owner	 }}";
            const repo = "${{ github.repository }}".split('/')[1]
            const prs = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              owner,
              repo,
              commit_sha: "${{ github.event.sha }}",
            });
            
            if (prs == null || prs.length === 0) {
              core.setFailed(`マージPRを取得できませんでした`);
              return;
            }

            const releasePr = await github.rest.pulls.get({
              owner,
              repo,
              pull_number: prs[0].number,
            });

            if (releasePr == null) {
              core.setFailed(`リリースPRを取得できませんでした`);
              return;
            }

            const body = releasePr.body;
            const match = body.match(/<!-- draft_release_id=(?<releaseId>.+) -->/);
            const releaseId = match?.groups?.releaseId;
            if (!releaseId) {
                core.setFailed(`リリースIDを取得できませんでした`);
                return;
            }

            core.debug(`releaseId: ${releaseId}`);
            
            await github.rest.repos.updateRelease({
              owner,
              repo,
              release_id: Number(releaseId),
              make_latest: 'true'
            });


