name: Confirm release

on:
  push:
    branches:
      - main

jobs:
  confirm_release:
    runs-on: ubuntu-latest
    steps:
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v2
      - name: Confirm release
        uses: actions/github-script@v6
        id: confirm-release
        with:
          script: |
            const owner = "${{ github.repository_owner	 }}";
            const repo = "${{ github.repository }}".split('/')[1];
            const {data: prs} = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              owner,
              repo,
              commit_sha: "${{ github.sha }}",
            });
            
            if (prs == null || prs.length === 0) {
              core.setFailed(`マージPRを取得できませんでした`);
              return;
            }

            const {data: releasePr} = await github.rest.pulls.get({
              owner,
              repo,
              pull_number: prs[0].number,
            });

            if (releasePr == null) {
              core.setFailed(`リリースPRを取得できませんでした`);
              return;
            }

            core.setOutput('releasePrLink', releasePr.html_url);

            const body = releasePr.body;
            const match = body.match(/<!-- draft_release_id=(?<releaseId>.+) -->/);
            const releaseId = match?.groups?.releaseId;
            if (!releaseId) {
                core.setFailed(`リリースIDを取得できませんでした`);
                return;
            }
            
            const {data: updatedRelease} = await github.rest.repos.updateRelease({
              owner,
              repo,
              release_id: Number(releaseId)
            });

            const changeLog = updatedRelease.body.replace("# What's Changed", `Release ${updatedRelease.name}`);

            core.setOutput('changelog', changeLog);
            core.setOutput('version', updatedRelease.name);
      - name: Make changelog file
        run: |
          echo "${{ steps.confirm-release.outputs.changelog }}" >> CHANGELOG.md
      - name: Create pr for attach changelog
        uses: peter-evans/create-pull-request@v4
        id: changelog-pr
        with:
          commit-message: Update Changelog
          branch: update-changelog
          delete-branch: true
          title: 'Update changelog for ${{ steps.confirm-release.outputs.version }}'
          body: "# 概要\\n${{ steps.confirm-release.outputs.releasePrLink }} のCHANGELOG反映PRです。"
          add-paths: CHANGELOG.md
      - uses: peter-evans/enable-pull-request-automerge@v2
        with:
          pull-request-number: ${{ steps.changelog-pr.outputs.pull-request-number }}

            


